<%!
from alembic import op
import sqlalchemy as sa
%>

-- commands auto generated by Alembic - please adjust! --

<% if up: %>
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
<% else: %>
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
<% endif %>